#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep 21 19:29:05 2020

@author: christoph
"""
import numpy as np


class Player():

    def __init__(self, rock, paper, scissors):
        self.rock = rock
        self.paper = paper
        self.scissors = scissors
        self.history = {}

    def rock_paper_scissors(self):

        # Make throw
        throw = np.random.choice(['Rock', 'Paper', 'Scissors'],
                                 p=[self.rock, self.paper, self.scissors])

        # Update history
        if throw not in self.history.keys():
            self.history[throw] = 1
        else:
            self.history[throw] += 1

        return throw


def evaluate_round(throw1, throw2):
    encoding_table = {'Rock': 0, 'Paper': 1, 'Scissors': 2}
    throw1 = encoding_table[throw1]
    throw2 = encoding_table[throw2]
    if (throw1 + 1) % 3 == throw2:
        return 2  # Player 2 won
    elif throw1 == throw2:
        return 0  # Nobody won
    else:
        return 1  # Player 1 won


p1 = Player(0.2, 0.3, 0.5)
p2 = Player(0.5, 0.2, 0.3)
# p3 = Player(0, 1, 0)
# p4 = Player(0.1, 0.2, 0.7)
players = [p1, p2]

hist = {'Player1': 0, 'Player2': 0}
for ii in range(0, 1000):

    print("###\tRound {idx}\t###".format(idx=ii))
    throws = ['', '']
    for jj, p in enumerate(players, start=0):
        throws[jj] = p.rock_paper_scissors()
        print("Player{idx}'s throw: {thr}".format(idx=jj + 1, thr=throws[jj]))

    result = evaluate_round(throws[0], throws[1])
    if result == 1:
        print("Player 1 won the round")
        hist['Player1'] += 1
    elif result == 2:
        print("Player 2 won the round")
        hist['Player2'] += 1
    else:
        print("It's a draw")

for i, p in enumerate(players, start=1):
    print("Player{idx}'s throw history: {hist}".format(idx=i, hist=p.history))
    print("Player{idx}'s win count: {wins}".format(idx=i, wins=hist['Player' + str(i)]))
